# Site settings
port: 4913

baseurl: "" 
url: "http://bio3ss.github.io" # the base hostname & protocol for your site

title: Bio 3SS, McMaster University
email: dushoff@mcmaster.ca
twitter_username: jd_mathbio

facebook: https://www.facebook.com/groups/967113330079615/
avenue: https://avenue.cllmcmaster.ca/d2l/home/273939

# Build settings
markdown: kramdown
