# Site settings
title: Bio 3SS, McMaster University
email: dushoff@mcmaster.ca
baseurl: "" 
url: "http://bio3ss.github.io" # the base hostname & protocol for your site
twitter_username: jd_mathbio

# Build settings
markdown: kramdown
